### PR TITLE
Wait

### PR DESCRIPTION
**Pull request by hunter**

### CODE REVIEW

**Comment by madziefe** [comment]
Changes:
  Added kontinuous wait api. 
  Added cli support for wait. 
If stage is wait, user will be ask to continue to next stage or not. If yes, will proceed to next stage. If no, the build is stopped.

**Comment by hunter** [comment]
Is an input required? Can the user come back later and resume? Important for cases of a manual testing stage (of unknown duration) that can then be pushed to production.

**Comment by darkcrux** [comment]
so wish we have TPR now. we could have kubectl as our cli tool. :D

**Comment by madziefe** [comment]
User input while current build is running and will encounter wait stage is supported. 
Resuming previously stopped builds is not yet supported. 

Should we add `resume` in cli command?
`kontinuous-cli resume <pipeline-name> --build 5`

**Comment by hunter** [comment]
Yes, I think that is a useful addition.

**Comment by madziefe** [comment]
Changes:
1. Wait api for Wait stage. (CLI and Dashboard)
   
   ```
   stage: Wait for confirmation
   type: wait
   ```
2. Kontinuous cli resume. Will resume current/previous waiting builds.
   
   `kontinuous-cli resume <pipeline-name> --build <build number>`

**Comment by hunter** [comment]
LGTM!!

**Comment by darkcrux** [comment]
mergin'

**Pull request merged**
